site_name: Jeux de rythme
site_url: https://jeuxderythme.fr
repo_url: https://github.com/jeuxderythme/jeuxderythme.github.io/

theme:
  name: material
  language: fr
  palette:
      # Toggle for auto mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-auto
        name: Passer en mode clair
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Passer en mode automatique
  features:
    - search.highlight
plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "jeuxderythme.fr, pour enfin savoir si le tasoller est mieux que le laverita"
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jeuxderythme/jeuxderythme.github.io
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/9RbS8Svx5m

nav:
  - Accueil: index.md
  - Arcaea: jeux/arcaea/arcaea.md
  - SOUND VOLTEX:
    - Le jeu: jeux/soundvoltex/soundvoltex.md
    - Les controllers: jeux/soundvoltex/controllers.md
    - Jouer sur PC: jeux/soundvoltex/logiciels.md
  - Comment progresser ?: progression.md
  - Les salles d'arcade: arcades.md
  - Les associations: associations.md
  - Contribuer: contribuer.md